---

- name: Install NFS server
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - nfs-utils


- name: Strart NFS server
  systemd:
    name: nfs-server
    state: started
    enabled: true
