---
- name: Change password for non-root users
  hosts: all
  become: true

  vars:
      new_password:"passwd1234"
  
  tasks:
    - name: Get list of users
      ansible.builtin.shell: "getent passwd | awk -F: '{print $1}'"
      register: users

    - name: Change password for non-root users
      user:
        name: "{{ item }}"
        password: "{{ new_password | password_hash('sha512') }}"
        update_password: always
      with_items: "{{ users.stdout_lines }}"
      when: item != 'root'
