---
- name: Install and start NFS server
  hosts: nfs_server
  become: true
  vars:
    nfs_share_path: /mnt/nfs_share
  tasks:
    - name: Install NFS server
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - nfs-utils
    - name: Start NFS server
      systemd:
        name: nfs-server
        state: started
        enabled: true